name = "nwsnumbot"
main = "index.js"
compatibility_date = "2026-03-08"

[[durable_objects.bindings]]
name = "ORDER_COUNTER"
class_name = "OrderCounter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["OrderCounter"]

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "CLIENTS"
id = "c638f4e8ab67463c9882857c8b93c063"

[[kv_namespaces]]
binding = "ORDERS_KV"
id = "25e034244f544889b450c9993e3c5370"

[vars]
MANAGER_ID = 1159166497
APP_URL = "https://krivetka13011.github.io/nws-app/"
WORKER_URL = "https://nwsnumbot.krivetkagames.workers.dev"
WEBHOOK_SECRET = "nws-secret-123"  # можно поменять на любое слово
# ID закрытой группы с темами (частная — только для менеджеров)
GROUP_ID = "-1003737384929"
# ID темы General (1 = стандартная тема для рассылок всем пользователям)
GENERAL_TOPIC_ID = "1"
# ImgBB API key — единственный вариант загрузки фото
IMGBB_KEY = "f38c7a675a4c700c9e8fa0885c5b36d2"