name = "nwsnumbot"
main = "index.js"
compatibility_date = "2026-03-08"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "CLIENTS"
id = "c638f4e8ab67463c9882857c8b93c063"

[[kv_namespaces]]
binding = "ORDERS_KV"
id = "25e034244f544889b450c9993e3c5370"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "nws-images"

[vars]
MANAGER_ID = 1159166497
APP_URL = "https://krivetka13011.github.io/nws-app/"
WORKER_URL = "https://nwsnumbot.krivetkagames.workers.dev"
WEBHOOK_SECRET = "nws-secret-123"
GROUP_ID = "-1003737384929"
GENERAL_TOPIC_ID = "1"
IMGBB_KEY = "412d2791dd8620104d0849b745f489e0"
